package com.pettrack.modules.ecommerce.domain.enums;

public enum StatusPedido {

    PEDIDO_CRIADO,
    AGUARDANDO_SEPARACAO,
    EM_SEPARACAO,
    AGUARDANDO_EMBALAGEM,
    EM_EMBALAGEM,
    EMBALADO,
    NA_GAIOLA,
    NO_PALLET,
    AGUARDANDO_TRANSPORTE,
    EM_TRANSITO_CD_FILIAL,
    RECEBIDO_NA_FILIAL,
    EM_SEPARACAO_FILIAL,
    EM_ROTA_ENTREGA,
    ENTREGUE,
    CANCELADO_ESTOQUE,
    CANCELADO_RETORNO_CD,
    CANCELAMENTO_BLOQUEADO,
    DEVOLUCAO_SOLICITADA,
    EM_DEVOLUCAO,
    DEVOLVIDO_AO_ESTOQUE

}