package com.pettrack.modules.ecommerce.domain.enums;

public enum SubregiaoFilial {

    // NORTE
    NORTE_AM,
    NORTE_PA,
    NORTE_AC,
    NORTE_RO,
    NORTE_RR,
    NORTE_AP,
    NORTE_TO,

    // NORDESTE
    NORDESTE_BA,
    NORDESTE_SE,
    NORDESTE_AL,
    NORDESTE_PE,
    NORDESTE_PB,
    NORDESTE_RN,
    NORDESTE_CE,
    NORDESTE_PI,
    NORDESTE_MA,

    // CENTRO-OESTE
    CENTRO_OESTE_GO,
    CENTRO_OESTE_MT,
    CENTRO_OESTE_MS,
    CENTRO_OESTE_DF,

    // SUDESTE
    SUDESTE_RJ,
    SUDESTE_MG,
    SUDESTE_ES,

    // SÃO PAULO (DIVISÃO PRÓPRIA POIS TEM UMA MAIOR CONCENTRAÇÃO DE DEMANDA)
    SAO_PAULO_CAPITAL_ZONA_NORTE,
    SAO_PAULO_CAPITAL_ZONA_SUL,
    SAO_PAULO_CAPITAL_ZONA_LESTE,
    SAO_PAULO_CAPITAL_ZONA_OESTE,
    SAO_PAULO_CAPITAL_ZONA_CENTRAL,
    SAO_PAULO_INTERIOR,
    SAO_PAULO_LITORAL,

    // SUL
    SUL_PR,
    SUL_SC,
    SUL_RS
}